# Meta Data for SEO

## Homepage
title = "Ardillo"
titleSeparator = "-"
titleAddition = "Asynchronous Desktop Applications with PHP"
description = "Ardillo is a PHP framework for building asynchronous desktop applications."

## Documentation
docsVersion = "0.1.x"

## Open Graph
images = ["logo-ardillo.png"]
ogLocale = "en_US"
domainTLD = "ardillo.dev"
titleHome = "Ardillo"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Ardillo"
schemaAuthor = "Ciprian Dosoftei"
schemaAuthorGitHub = "https://github.com/ardillo-php"
schemaLocale = "en-US"
schemaLogo = "logo-ardillo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "logo-ardillo.png"
schemaImageWidth = 512
schemaImageHeight = 512
schemaGitHub = "https://github.com/ardillo-php"
schemaSection = "docs"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = ""

# Feed
copyRight = "Copyright (c) 2023 Ciprian Dosoftei"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/ardillo-php/ardillo.dev"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = true
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
